export const PlansItems = [
  {
    text: "Plano Patriota",
    href: "http://localhost:3001",
    badge: {
      badgeText: "Popular",
      badgeClassName: "shelfBadgePopular",
    },
    valueInCents: 1900,
    recurrence: "MONTHLY",
    packageContents: "Produções originais e programas",
    buttonText: "Assinar Plano Patriota",
    contents: "Nosso plano inicial",
    features: [
      "Access to basic features",
      "Basic reporting and analytics",
      "Up to 10 individual users",
    ],
  },
  {
    text: "Plano BP Select",
    href: "http://localhost:3001",
    valueInCents: 2900,
    recurrence: "MONTHLY",
    packageContents: "Nosso streaming de filmes e desenhos",
    buttonText: "Assinar BP Select",
    contents: "Plano patriota mais...",
    features: [
      "200+ integrations",
      "Advanced reporting and analytics and custom fields",
      "Up to 20 individuals users",
      "40GB individual data each user",
    ],
  },
  {
    text: "Plano Acesso Total",
    href: "http://localhost:3001",
    valueInCents: 9900,
    recurrence: "MONTHLY",
    packageContents: "Todo o conteúdo do Brasil Paralelo",
    buttonText: "Assinar Acesso Total",
    contents: ["O melhor plano do Brasil Paralelo.", "Todo conteúdo em uma única assinatura."],
    features: [
      "Advanced custom fields",
      "Audit log and data history",
      "Unlimited individual users",
      "Unlimited individual data",
      "Personalised+priority service",
    ],
  },
]
